/**
 * Runtime configuration for an Angular application.
 *
 * THIS IS THE FILE THE BLUEPRINT EXISTS TO PRODUCE.
 *
 * A naive Angular build substitutes environment values at COMPILE time —
 * typically through `environment.ts` and a file-replacement in
 * `angular.json`. That produces a DIFFERENT ARTIFACT PER ENVIRONMENT, which
 * breaks build-once promotion: the bundle deployed to production is not the
 * bundle UAT verified.
 *
 * Instead, the container writes `assets/config.json` at start from
 * environment variables (see templates/docker/runtime-config.angular.sh),
 * and the application fetches it before bootstrapping. One image is promoted
 * unchanged to DEV, UAT, and PROD.
 *
 * See docs/01-architecture/environment-architecture.md
 */

export type Environment = 'dev' | 'uat' | 'prod';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export interface RuntimeConfig {
  readonly apiBaseUrl: string;
  readonly environment: Environment;
  readonly logLevel: LogLevel;
  readonly featureFlags: Readonly<Record<string, boolean>>;
}

/** Where the entrypoint script writes the file. */
export const CONFIG_URL = '/assets/config.json';

const ENVIRONMENTS: readonly Environment[] = ['dev', 'uat', 'prod'];
const LOG_LEVELS: readonly LogLevel[] = ['debug', 'info', 'warn', 'error'];

/**
 * Fetches and validates the runtime configuration.
 *
 * FAILS rather than falling back to a default. A default that points at a
 * real environment starts successfully and is discovered later, as incorrect
 * behaviour — which is worse than not starting. The failure mode of missing
 * configuration must be "does not start".
 *
 * See docs/06-container/docker-standard.md, requirement C9.
 */
export async function loadRuntimeConfig(
  fetchFn: typeof fetch = fetch,
  url: string = CONFIG_URL,
): Promise<RuntimeConfig> {
  // `cache: 'no-store'` matters. Cached, a promoted container would serve the
  // PREVIOUS environment's configuration from the browser cache — the nginx
  // configuration sets no-store for the same reason, and both are needed
  // because either alone can be bypassed.
  const response = await fetchFn(url, { cache: 'no-store' });

  if (!response.ok) {
    throw new Error(
      `Runtime configuration could not be loaded from ${url} (HTTP ${response.status}). ` +
        'The container entrypoint may not have run — check that the script in ' +
        '/docker-entrypoint.d is executable.',
    );
  }

  const raw: unknown = await response.json();
  return validateRuntimeConfig(raw);
}

/**
 * Validates the shape and values.
 *
 * The file is generated by a shell script from environment variables, so
 * every field arrives as whatever was set — including nothing. Validating
 * here turns a silent misconfiguration into a startup failure with a message
 * that names the field.
 */
export function validateRuntimeConfig(raw: unknown): RuntimeConfig {
  if (typeof raw !== 'object' || raw === null) {
    throw new Error('Runtime configuration is not an object.');
  }

  const candidate = raw as Record<string, unknown>;
  const missing: string[] = [];

  const apiBaseUrl = candidate['apiBaseUrl'];
  if (typeof apiBaseUrl !== 'string' || apiBaseUrl.length === 0) {
    missing.push('apiBaseUrl');
  }

  const environment = candidate['environment'];
  if (typeof environment !== 'string' || !ENVIRONMENTS.includes(environment as Environment)) {
    missing.push(`environment (expected one of: ${ENVIRONMENTS.join(', ')})`);
  }

  const logLevel = candidate['logLevel'];
  const resolvedLogLevel: LogLevel =
    typeof logLevel === 'string' && LOG_LEVELS.includes(logLevel as LogLevel)
      ? (logLevel as LogLevel)
      : 'warn';

  const featureFlags = candidate['featureFlags'];
  const resolvedFlags: Record<string, boolean> = {};
  if (featureFlags !== undefined) {
    if (typeof featureFlags !== 'object' || featureFlags === null) {
      missing.push('featureFlags (expected an object)');
    } else {
      for (const [key, value] of Object.entries(featureFlags as Record<string, unknown>)) {
        if (typeof value !== 'boolean') {
          missing.push(`featureFlags.${key} (expected a boolean)`);
        } else {
          resolvedFlags[key] = value;
        }
      }
    }
  }

  if (missing.length > 0) {
    // Names the fields. Never echoes values — this message can reach a
    // browser console and an error report.
    throw new Error(`Runtime configuration is invalid: ${missing.join(', ')}`);
  }

  return {
    apiBaseUrl: apiBaseUrl as string,
    environment: environment as Environment,
    logLevel: resolvedLogLevel,
    featureFlags: Object.freeze(resolvedFlags),
  };
}
